# Generated by Django 5.2.7 on 2025-10-09 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('first_line', models.CharField(max_length=80)),
                ('second_line', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=25)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('default_address', models.BooleanField(default=False)),
                ('billing_address', models.BooleanField(default=False)),
                ('delivery_address', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
