# Generated by Django 5.2.7 on 2025-10-10 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, help_text='Optional name, e.g. Home or Work Address', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='default_billing_address',
            field=models.ForeignKey(blank=True, help_text='User’s preferred billing address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_billing_address', to='profiles.address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_delivery_address',
            field=models.ForeignKey(blank=True, help_text='User’s preferred delivery address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_delivery_address', to='profiles.address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact Number (Optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
