# Generated by Django 5.2.7 on 2025-11-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
    ]
